version: '{build}'
os: Windows Server 2012
environment:
    matrix:
        - JAVA_HOME: C:\Program Files\Java\jdk1.7.0
        - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
				
test_script:
  - mvn --batch-mode clean package